// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFhlOiVbWLCqpUPFEkkyiLwKTnvXusDQg',
    appId: '1:460181292669:web:88fe9926f274c9a47d5314',
    messagingSenderId: '460181292669',
    projectId: 'com-example-service-locator',
    authDomain: 'com-example-service-locator.firebaseapp.com',
    storageBucket: 'com-example-service-locator.firebasestorage.app',
    measurementId: 'G-9DQDN786ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgc_7_z1PoNuFhyu0mnX3_pMTH942njL4',
    appId: '1:460181292669:android:d872d8c297acbe877d5314',
    messagingSenderId: '460181292669',
    projectId: 'com-example-service-locator',
    storageBucket: 'com-example-service-locator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4sVYtW0CDkCzVv0xMjivvTPNmPMYnJJs',
    appId: '1:460181292669:ios:10e8c2932fb0c5547d5314',
    messagingSenderId: '460181292669',
    projectId: 'com-example-service-locator',
    storageBucket: 'com-example-service-locator.firebasestorage.app',
    iosBundleId: 'com.smartride.smartRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4sVYtW0CDkCzVv0xMjivvTPNmPMYnJJs',
    appId: '1:460181292669:ios:10e8c2932fb0c5547d5314',
    messagingSenderId: '460181292669',
    projectId: 'com-example-service-locator',
    storageBucket: 'com-example-service-locator.firebasestorage.app',
    iosBundleId: 'com.smartride.smartRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFhlOiVbWLCqpUPFEkkyiLwKTnvXusDQg',
    appId: '1:460181292669:web:f90220c62d0404d47d5314',
    messagingSenderId: '460181292669',
    projectId: 'com-example-service-locator',
    authDomain: 'com-example-service-locator.firebaseapp.com',
    storageBucket: 'com-example-service-locator.firebasestorage.app',
    measurementId: 'G-B13ENHLMPF',
  );
}
